### ISSUE TITLE
does not compile on 10.10 with Xcode 6.2

### ISSUE THREAD

**Issue by dave256** [djthorpe/postgresql-kit#14]
I'm interested in trying this out so I did this on a 10.10 machine with Xcode 6.2 and its commandline tools installed.

cd etc
./build-macapps.sh 

and it failed. Here's the end of the output

CompileC build/postgresql-kit.build/Release/PGFoundationClient.build/Objects-normal/x86_64/PGFoundationClient2.o src/Apps/Foundation/PGFoundationClient2.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
    cd /Users/dreed/Projects/postgresql-kit
    export LANG=en_US.US-ASCII
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -x objective-c -arch x86_64 -fmessage-length=80 -fdiagnostics-show-note-include-stack -fmacro-backtrace-limit=0 -fcolor-diagnostics -std=gnu99 -fobjc-arc -Wno-trigraphs -fpascal-strings -Os -Wno-missing-field-initializers -Wno-missing-prototypes -Wno-implicit-atomic-properties -Wno-receiver-is-weak -Wno-arc-repeated-use-of-weak -Wduplicate-method-match -Wno-missing-braces -Wparentheses -Wswitch -Wno-unused-function -Wno-unused-label -Wno-unused-parameter -Wunused-variable -Wunused-value -Wno-empty-body -Wuninitialized -Wno-unknown-pragmas -Wno-shadow -Wno-four-char-constants -Wno-conversion -Wno-constant-conversion -Wno-int-conversion -Wno-bool-conversion -Wno-enum-conversion -Wshorten-64-to-32 -Wpointer-sign -Wno-newline-eof -Wno-selector -Wno-strict-selector-match -Wno-undeclared-selector -Wno-deprecated-implementations -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -fasm-blocks -fstrict-aliasing -Wprotocol -Wdeprecated-declarations -mmacosx-version-min=10.9 -g -fvisibility=hidden -Wno-sign-conversion -I/Users/dreed/Projects/postgresql-kit/build/postgresql-kit.build/Release/PGFoundationClient.build/PGFoundationClient.hmap -I/Users/dreed/Projects/postgresql-kit/build/Release/include -I/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/include -I/Users/dreed/Projects/postgresql-kit/build/postgresql-kit.build/Release/PGFoundationClient.build/DerivedSources/x86_64 -I/Users/dreed/Projects/postgresql-kit/build/postgresql-kit.build/Release/PGFoundationClient.build/DerivedSources -F/Users/dreed/Projects/postgresql-kit/build/Release -MMD -MT dependencies -MF /Users/dreed/Projects/postgresql-kit/build/postgresql-kit.build/Release/PGFoundationClient.build/Objects-normal/x86_64/PGFoundationClient2.d --serialize-diagnostics /Users/dreed/Projects/postgresql-kit/build/postgresql-kit.build/Release/PGFoundationClient.build/Objects-normal/x86_64/PGFoundationClient2.dia -c /Users/dreed/Projects/postgresql-kit/src/Apps/Foundation/PGFoundationClient2.m -o /Users/dreed/Projects/postgresql-kit/build/postgresql-kit.build/Release/PGFoundationClient.build/Objects-normal/x86_64/PGFoundationClient2.o

Ld build/Release/PGFoundationClient normal x86_64
    cd /Users/dreed/Projects/postgresql-kit
    export MACOSX_DEPLOYMENT_TARGET=10.9
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.9.sdk -L/Users/dreed/Projects/postgresql-kit/build/Release -F/Users/dreed/Projects/postgresql-kit/build/Release -filelist /Users/dreed/Projects/postgresql-kit/build/postgresql-kit.build/Release/PGFoundationClient.build/Objects-normal/x86_64/PGFoundationClient.LinkFileList -mmacosx-version-min=10.9 -fobjc-arc -fobjc-link-runtime -framework PGClientKit -framework Foundation -ledit.3 -Xlinker -dependency_info -Xlinker /Users/dreed/Projects/postgresql-kit/build/postgresql-kit.build/Release/PGFoundationClient.build/Objects-normal/x86_64/PGFoundationClient_dependency_info.dat -o /Users/dreed/Projects/postgresql-kit/build/Release/PGFoundationClient
ld: framework not found PGClientKit
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **

The following build commands failed:
	CompileC build/postgresql-kit.build/Release/PGClientKit_mac.build/Objects-normal/x86_64/PGQuery.o src/Frameworks/PGClientKit/PGQuery.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/postgresql-kit.build/Release/PGClientKit_mac.build/Objects-normal/x86_64/PGQueryCreate.o src/Frameworks/PGClientKit/PGQueryCreate.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	CompileC build/postgresql-kit.build/Release/PGClientKit_mac.build/Objects-normal/x86_64/PGSelect.o src/Frameworks/PGClientKit/PGSelect.m normal x86_64 objective-c com.apple.compilers.llvm.clang.1_0.compiler
	MasterObjectLink build/postgresql-kit.build/Release/PGClientKit_mac.build/Objects-normal/PGClientKit-x86_64-master.o
	Ld build/Release/PGClientKit.framework/Versions/A/PGClientKit normal x86_64
	Ld build/Release/PGFoundationClient normal x86_64
(6 failures)

**Comment by djthorpe** [comment]
Hi Dave, can you checkout the "dev" branch instead, that one has a working version of PGClientKit. I'm just getting close to the point of releasing a new alpha version of the framework. Let me know how that goes.

**Comment by dave256** [comment]
Yes, the dev branch compiled for me. I don't have any time right now to do more with it, but I look forward to trying it when I have time. Thanks!

**Comment by djthorpe** [comment]
Thanks. I'll merge the dev branch with the master branch today, and create a .ZIP with the latest compiled version in it. Please do let me know if you have any further questions.
