### ISSUE TITLE
PGClientKit.framework/Headers/PGClientKit.h:33:9: 'PGResult+TextTable.h' file not found

### ISSUE THREAD

**Issue by crowdmatt** [djthorpe/postgresql-kit#5]
Dragged and dropped `PGClientKit.framework` file inside my Mac OS X project (from the "postgresql-kit pre release v5" zip file at: https://github.com/djthorpe/postgresql-kit/releases/download/alpha-005/release-postgresql-kit-alpha005.zip )

When I simply include `#import <PGClientKit/PGClientKit.h>` into my AppDelegate, and try to compile, I get the following error: 

/Users/myusername/Projects/mypgapp/PGClientKit.framework/Headers/PGClientKit.h:33:9: 'PGResult+TextTable.h' file not found

Any idea?

**Comment by djthorpe** [comment]
This is fixed in the current dev branch!
