### ISSUE TITLE
compiled Project

### ISSUE THREAD

**Issue by pschwalb** [djthorpe/postgresql-kit#9]
Hi
I am interested in your brilliant project
but I would prefer to get the compiled project instead of compile it myself.
the reason is that I don't know what installation of Xcode you have and how you solved ( a lot of missing Headerfiles (System) this problems or maybe you never had them.
 
So if you could post the usable Frameworks and so on I could concentrate on my Project with the help of your Project
Thanks in advance

**Comment by djthorpe** [comment]
Hi all, I know I am hideously late here, but the project does now compile correctly, The latest version is tagged here: https://github.com/djthorpe/postgresql-kit/releases

I'm going to close this bug for now, and if there are further issues with compiling, please open another specifically with the issue you're having (logs from your build attempt, etc) and I will take a look.
